# TODO: replace the title with the name of your restaurant!
title: "Villa Borghese"
# TODO: write your restaurateur alter ego name below, or your own name
author: 
# TODO: write your Google Analytics tracking ID below
google_analytics: G-275D3NL1MK

theme: minima

collections:
  explorations:
    output: true
